name: sliver_passthrough
description: "Utility package that provides a seamless way to use box widgets sandwiched between slivers"
version: 0.1.0

repository: 'https://github.com/NikolayNIK/sliver_passthrough'
issue_tracker: 'https://github.com/NikolayNIK/sliver_passthrough/issues'

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
